import{buildICTContext}from"./ict.js";
export const PROMPT_VERSION="1.11.0";
const cap={current_m5:64,history_m15:32,history_h1:32,history_h4:32,historical_1y:30};
const ema=(a,n)=>{if(a.length<n)return undefined;let e=a.slice(0,n).reduce((x,c)=>x+c.close,0)/n,k=2/(n+1);for(let i=n;i<a.length;i++)e=a[i].close*k+e*(1-k);return e};
const stats=c=>{const closes=c.map(x=>x.close),ranges=c.map(x=>x.high-x.low);let gains=0,losses=0;for(let i=1;i<closes.length;i++){const d=closes[i]-closes[i-1];if(d>0)gains+=d;else if(d<0)losses-=d}const rsi=losses?100-100/(1+(gains/Math.max(1,closes.length-1))/(losses/Math.max(1,closes.length-1))):100;const tr=ranges.slice(-14).reduce((a,b)=>a+b,0)/Math.max(1,ranges.slice(-14).length);const hi=Math.max(...c.map(x=>x.high)),lo=Math.min(...c.map(x=>x.low));const out={candles_count:c.length,ema20:ema(c,20),ema50:ema(c,50),rsi14:rsi,atr14:c.length>=14?tr:undefined,atr_pct:c.length>=14?tr/(closes.at(-1)||1)*100:undefined,range_pos_pct:(closes.at(-1)-lo)/(hi-lo||1)*100,};for(let i=c.length-2;i>=1;i--){if(c[i].high>c[i-1].high&&c[i].high>c[i+1].high){out.swing_high=[c[i].high,c.length-1-i];break}}return out};
const encode=(c,n,stepMin)=>{const x=c.slice(-n),o={candles_fetched:c.length,candles_included:x.length,step_min:stepMin,start:x.length?new Date(x[0].timestamp).toISOString():undefined,candles:x.map((v,i)=>[i,v.open,v.high,v.low,v.close,v.volume]),statistics:stats(c)};o.indicators=stats(c);if(stepMin===5)o.indicators.vwap_window=c.length?c.reduce((a,x)=>a+x.close*x.volume,0)/Math.max(1,c.reduce((a,x)=>a+x.volume,0)):undefined;if(c.length>x.length)o.note="Only the most recent candles are included.";return o};
function dailyLevels(c){const closed=c.filter(x=>x.closed!==false);if(!closed.length)return null;const today=c.at(-1)?.closed===false?c.at(-1):null,prev=closed.at(-1),week=closed.slice(-7),month=closed.slice(-30),year=closed,idxH=year.reduce((a,x,i)=>x.high>year[a].high?i:a,0),idxL=year.reduce((a,x,i)=>x.low<year[a].low?i:a,0);return{...(today?{today:{high:today.high,low:today.low}}:{}),prev_day:{high:prev.high,low:prev.low,close:prev.close},week_7d:{high:Math.max(...week.map(x=>x.high)),low:Math.min(...week.map(x=>x.low))},month_30d:{high:Math.max(...month.map(x=>x.high)),low:Math.min(...month.map(x=>x.low))},year:{high:Math.max(...year.map(x=>x.high)),low:Math.min(...year.map(x=>x.low)),high_days_ago:year.length-1-idxH,low_days_ago:year.length-1-idxL,days:year.length}}}
export function buildPrompt(snap={},record=null){const m5=snap.candles||[],m15=snap.history_m15||[],h1=snap.history_h1||[],h4=snap.history_h4||[],d1=snap.history_1d||[];const data={exchange:snap.exchange,symbol:snap.symbol,current_m5:encode(m5,cap.current_m5,5),history_m15:encode(m15,cap.history_m15,15),history_h1:encode(h1,cap.history_h1,60),history_h4:encode(h4,cap.history_h4,240),historical_1y:encode(d1,cap.historical_1y,1440),key_levels:dailyLevels(d1),ict:buildICTContext({m5,m15,h1,h4}),signal_track_record:record||null};if(snap.derivatives)data.derivatives=snap.derivatives;const system="You are an AI market analyst using a deterministic ICT-style multi-timeframe framework. Never infer a trend from a single snapshot.";const user=`NEXT 1-4 HOURS
ICT ANALYSIS CONTRACT
Do not invent an FVG, OB, sweep, BOS, CHOCH, MSS.
MARKET DATA (JSON):
${JSON.stringify(data)}

Candle schema: [k, o, h, l, c, v]
Derivatives fields such as funding_rate_pct are context only; never infer a trend from a single snapshot. signal_track_record describes past votes and is weak context.
NO_TRADE when evidence is insufficient or atr14/context does not support a directional setup.`;return{system,user}}