import { describe, it, expect } from "vitest";
import { computeVoting } from "../src/orchestrator/voting.js";
function result(signal, status = "success") { return { status, signal }; }
describe("computeVoting", () => {
  it("computes majority BUY correctly", () => { const v=computeVoting([result("BUY"),result("BUY"),result("SELL"),result("BUY"),result("NO_TRADE"),result("BUY")]); expect(v.buy).toBe(4); expect(v.sell).toBe(1); expect(v.no_trade).toBe(1); expect(v.majority_signal).toBe("BUY"); expect(v.decision_reason).toBe("MAJORITY"); expect(v.total_models).toBe(6); expect(v.success).toBe(6); });
  it("only counts SUCCESS results in voting", () => { const v=computeVoting([result("BUY"),result("BUY"),{status:"timeout",signal:null},result("BUY"),result("SELL"),{status:"error",signal:null}]); expect(v.total_models).toBe(6); expect(v.success).toBe(4); expect(v.error).toBe(2); expect(v.buy).toBe(3); expect(v.majority_signal).toBe("BUY"); });
  it("resolves a BUY/SELL tie to NO_TRADE", () => { const v=computeVoting([result("BUY"),result("BUY"),result("SELL"),result("SELL")]); expect(v.majority_signal).toBe("NO_TRADE"); expect(v.decision_reason).toBe("VOTE_TIE"); });
  it("treats NO_TRADE plurality as majority", () => { const v=computeVoting([result("NO_TRADE"),result("NO_TRADE"),result("NO_TRADE"),result("BUY"),result("SELL")]); expect(v.majority_signal).toBe("NO_TRADE"); expect(v.decision_reason).toBe("MODEL_NO_TRADE"); });
  it("returns NO_TRADE when all providers fail", () => { const v=computeVoting([{status:"error",signal:null},{status:"timeout",signal:null}]); expect(v.majority_signal).toBe("NO_TRADE"); expect(v.decision_reason).toBe("NO_VALID_VOTES"); expect(v.success).toBe(0); });
  it("never labels vote share as confidence and computes correct percentages", () => { const v=computeVoting([result("BUY"),result("BUY"),result("SELL"),result("NO_TRADE")]); expect(v.buy_vote_share).toBe(50); expect(v.sell_vote_share).toBe(25); expect(v.no_trade_vote_share).toBe(25); expect(v).not.toHaveProperty("confidence"); });
});
describe("weighted voting",()=>{it("uses model confidence when available",()=>{const v=computeVoting([{status:"success",provider:"a",signal:"BUY",confidence:1},{status:"success",provider:"b",signal:"SELL",confidence:0}]);expect(v.majority_signal).toBe("BUY");expect(v.weighted_buy).toBeGreaterThan(v.weighted_sell);});it("allows explicit provider weights",()=>{const v=computeVoting([{status:"success",provider:"a",signal:"BUY"},{status:"success",provider:"b",signal:"SELL"}],{weights:{b:2}});expect(v.majority_signal).toBe("SELL");});});