#!/usr/bin/env python3
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD = ROOT / "dashboard"
ICONS = DASHBOARD / "icons"
ICONS.mkdir(parents=True, exist_ok=True)

MASTER = 1024
NAVY = "#071426"
NAVY_2 = "#0A2A54"
CYAN = "#27C5F9"
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
]

def get_font(size):
    for path in FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, size=size)
    return ImageFont.load_default()

def draw_master(maskable=False):
    image = Image.new("RGBA", (MASTER, MASTER), NAVY if maskable else (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    if maskable:
        draw.rounded_rectangle((176, 176, 848, 848), radius=168, fill=NAVY_2, outline=CYAN, width=6)
        font = get_font(340)
        dot = (768, 252, 804, 288)
    else:
        draw.rounded_rectangle((0, 0, 1023, 1023), radius=232, fill=NAVY)
        draw.rounded_rectangle((68, 68, 955, 955), radius=196, fill=NAVY_2)
        draw.rounded_rectangle((144, 144, 880, 880), radius=184, outline=CYAN, width=6)
        font = get_font(380)
        dot = (784, 200, 824, 240)
    label = "BG"
    box = draw.textbbox((0, 0), label, font=font)
    width = box[2] - box[0]
    height = box[3] - box[1]
    y_adjust = 18 if maskable else 24
    draw.text(((MASTER - width) / 2, (MASTER - height) / 2 - box[1] + y_adjust), label, font=font, fill=CYAN)
    draw.ellipse(dot, fill=CYAN)
    return image

def save_scaled(master, size, path):
    master.resize((size, size), Image.Resampling.LANCZOS).save(path, "PNG", optimize=True)

normal = draw_master(False)
maskable = draw_master(True)
save_scaled(normal, 128, DASHBOARD / "byga-logo.png")
save_scaled(normal, 64, DASHBOARD / "favicon.png")
for size in (16, 32, 64):
    save_scaled(normal, size, DASHBOARD / f"favicon-{size}.png")
save_scaled(normal, 180, DASHBOARD / "apple-touch-icon.png")
save_scaled(normal, 192, ICONS / "pwa-192.png")
save_scaled(normal, 512, ICONS / "pwa-512.png")
save_scaled(maskable, 192, ICONS / "maskable-192.png")
save_scaled(maskable, 512, ICONS / "maskable-512.png")
print("Generated BYGA primary logo, favicon, Apple touch and PWA icon set.")
